# Generated by Django 6.0 on 2025-12-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='cars/'),
        ),
    ]
